export function downloadAsHTML(article, chosenImages) {
  const bodyWithImages = article.body?.map((para, i) => {
    const imageHTML = chosenImages?.[Math.floor(i / 2)] && i % 2 === 1
      ? `<div style="margin:24px 0;text-align:center;">
          <img src="${chosenImages[Math.floor(i/2)].url}" alt="${chosenImages[Math.floor(i/2)].description||''}" style="max-width:100%;height:auto;border-radius:8px;" crossorigin="anonymous"/>
          <p style="color:#888;font-size:0.8em;margin-top:6px;">Photo by ${chosenImages[Math.floor(i/2)].photographer} on ${chosenImages[Math.floor(i/2)].source}</p>
        </div>`
      : ''
    return `<p>${para}</p>${imageHTML}`
  }).join('') || ''

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${article.headline}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.8; }
    h1 { font-size: 2em; margin-bottom: 10px; }
    .lede { font-size: 1.2em; color: #444; border-left: 4px solid #3b82f6; padding-left: 16px; margin-bottom: 24px; font-style: italic; }
    .body p { margin-bottom: 16px; }
    .background { background: #f5f5f5; padding: 16px; border-radius: 8px; margin: 24px 0; }
    .quote { border-left: 4px solid #f59e0b; padding-left: 16px; margin: 16px 0; font-style: italic; color: #555; }
    .warning { color: #d97706; font-size: 0.8em; }
    .tag { display: inline-block; background: #dbeafe; color: #1d4ed8; padding: 4px 12px; border-radius: 999px; font-size: 0.8em; margin-right: 6px; }
    .meta { color: #888; font-size: 0.85em; margin-top: 16px; }
    img { max-width: 100%; height: auto; }
  </style>
</head>
<body>
  <div>${article.tags?.map(t => `<span class="tag">${t}</span>`).join('') || ''}</div>
  <h1>${article.headline}</h1>
  <div class="lede">${article.lede}</div>
  <div class="body">${bodyWithImages}</div>
  ${article.background ? `<div class="background"><strong>Background and Context</strong><p>${article.background}</p></div>` : ''}
  ${article.quotes?.map(q => `<div class="quote"><p>"${q}"</p><div class="warning">AI-generated quote, verify before publishing</div></div>`).join('') || ''}
  <div class="meta">Word count: ${article.word_count} | Generated by NewsDraft AI</div>
</body>
</html>`
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${article.headline?.replace(/[^a-z0-9]/gi, '_')}.html`
  a.click()
  URL.revokeObjectURL(url)
}

export function downloadAsPDF(article, chosenImages) {
  const bodyWithImages = article.body?.map((para, i) => {
    const imageHTML = chosenImages?.[Math.floor(i / 2)] && i % 2 === 1
      ? `<div style="margin:24px 0;text-align:center;">
          <img src="${chosenImages[Math.floor(i/2)].url}" alt="${chosenImages[Math.floor(i/2)].description||''}" style="max-width:100%;height:auto;border-radius:8px;display:block;margin:0 auto;" crossorigin="anonymous"/>
          <p style="color:#888;font-size:0.8em;margin-top:6px;">Photo by ${chosenImages[Math.floor(i/2)].photographer} on ${chosenImages[Math.floor(i/2)].source}</p>
        </div>`
      : ''
    return `<p>${para}</p>${imageHTML}`
  }).join('') || ''

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${article.headline}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:Georgia,'Times New Roman',serif; max-width:750px; margin:40px auto; padding:0 30px; color:#1a1a1a; line-height:1.9; font-size:16px; }
    .tags { margin-bottom:16px; }
    .tag { display:inline-block; background:#dbeafe; color:#1d4ed8; padding:3px 10px; border-radius:999px; font-size:0.75em; margin-right:6px; margin-bottom:6px; }
    h1 { font-size:2em; margin-bottom:16px; line-height:1.3; color:#111; }
    .lede { font-size:1.15em; color:#444; border-left:4px solid #3b82f6; padding-left:16px; margin-bottom:28px; font-style:italic; }
    .body p { margin-bottom:18px; text-align:justify; }
    .body img { max-width:100%; height:auto; border-radius:8px; display:block; margin:0 auto; }
    .background { background:#f8f8f8; padding:16px 20px; border-radius:8px; margin:24px 0; border-left:4px solid #94a3b8; }
    .background strong { display:block; margin-bottom:8px; color:#555; font-size:0.85em; text-transform:uppercase; }
    .quote { border-left:4px solid #f59e0b; padding:12px 16px; margin:20px 0; background:#fffbeb; border-radius:0 8px 8px 0; }
    .quote p { font-style:italic; color:#555; margin-bottom:6px; }
    .warning { color:#d97706; font-size:0.78em; }
    .meta { color:#999; font-size:0.82em; margin-top:32px; border-top:1px solid #eee; padding-top:16px; }
    img { max-width:100%; height:auto; }
    @media print { body { margin:20px; } img { max-width:100%!important; page-break-inside:avoid; } }
  </style>
</head>
<body>
  <div class="tags">${article.tags?.map(t => `<span class="tag">${t}</span>`).join('') || ''}</div>
  <h1>${article.headline}</h1>
  <div class="lede">${article.lede}</div>
  <div class="body">${bodyWithImages}</div>
  ${article.background ? `<div class="background"><strong>Background and Context</strong><p>${article.background}</p></div>` : ''}
  ${article.quotes?.length > 0 ? article.quotes.map(q => `<div class="quote"><p>"${q}"</p><div class="warning">AI-generated quote, verify before publishing</div></div>`).join('') : ''}
  <div class="meta">Word count: ${article.word_count} | Generated by NewsDraft AI | ${new Date().toLocaleDateString()}</div>
</body>
</html>`

  const printWindow = window.open('', '_blank')
  printWindow.document.write(html)
  printWindow.document.close()

  printWindow.onload = () => {
    const images = printWindow.document.querySelectorAll('img')
    if (images.length === 0) {
      setTimeout(() => { printWindow.print(); printWindow.close() }, 300)
      return
    }
    let loadedCount = 0
    const checkAllLoaded = () => {
      loadedCount++
      if (loadedCount >= images.length) {
        setTimeout(() => { printWindow.print(); printWindow.close() }, 500)
      }
    }
    images.forEach(img => {
      if (img.complete) checkAllLoaded()
      else { img.onload = checkAllLoaded; img.onerror = checkAllLoaded }
    })
  }
}